### ISSUE TITLE
Error when sending in StatsD metrics to CollectdWin

### ISSUE THREAD

**Issue by Grumblesmith** [Netuitive/collectdwin#12]
2017-04-17 13:12:58.3698|ERROR|BloombergFLP.CollectdWin.MetricsCollector: Exception in ReadThreadProc()
EXCEPTION: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[BloombergFLP.CollectdWin.MetricValue]' to type 'System.Collections.Generic.IList`1[BloombergFLP.CollectdWin.CollectableValue]'.
   at BloombergFLP.CollectdWin.ReadStatsdPlugin.Read()
   at BloombergFLP.CollectdWin.MetricsCollector.ReadThreadProc()

**Comment by Grumblesmith** [comment]
@andrewpaine message me if you have time to take a look at this tomorrow. I can give you the details of the environment where I have this reproduced

**Comment by Grumblesmith** [comment]
Closing. Opened as https://github.com/Netuitive/netuitive-windows-agent/issues/3
